### ISSUE TITLE
Account setup earlier

### ISSUE THREAD

**Issue by CodeSchwert** [Developers-Institute/WDD01-Client-Side-Pre-Course-Setup#7]
Maybe one of the first steps could be to set up a Pluralsight account. There are some good intro courses, like https://app.pluralsight.com/library/courses/git-big-picture, but they would need a Pluralsight account to watch.

Currently, Git is on Day 2, but account set up is on Day 3.

**Comment by lwcooper** [comment]
Fixed https://github.com/Developers-Institute/WDD01-Client-Side-Pre-Course-Setup/pull/1
